version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: "Asia/Tokyo"
    ports:
      - 3304:3306
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  minio:
    image: quay.io/minio/minio:latest
    container_name: example-minio
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001